### ISSUE TITLE
Can you provide support for 64-bit also?

### ISSUE THREAD

**Issue by abhijeet0** [lufinkey/react-native-spotify#172]
Thank you for contributing to `rn-spotify-sdk`!

Be sure to include your react-native version, platform you're developing for, and iOS or Android version.

Please do not open issues about getting the module to work unless you have tried using both the example app and the example token swap server. Please make sure you have tried running on the latest react-native version before submitting a bug.

**Comment by Abhijeet0** [comment]
@bdilly @yamalight @adebree @grabbou  I'm getting error on latest devices which supports 64-bit. Can you provide details for this or is it a bug?

**Comment by Abhijeet0** [comment]
@lufinkey I'm getting error on latest devices which supports 64-bit. Can you provide details for this or is it a bug?

**Comment by lufinkey** [comment]
Hey sorry for the lack of response on this. 64-bit devices should be supported, but it's entirely dependent on the Spotify Streaming SDK binaries that this library uses. Since those libraries are deprecated, unfortunately I can't make that change. But I believe you can make changes to your packaging options in gradle to fix which versions of the library get selected
