### ISSUE TITLE
playURI promise doesn't update the PlaybackState and PlaybackMetaData object synchronously

### ISSUE THREAD

**Issue by Abdul-Miraj** [lufinkey/react-native-spotify#63]
After playing a song using the playURI function and evaluating the callback with a .then, the PlaybackState and PlaybackMetadata inside the .then is  not being the updated.

```
Spotify.playURI('spotify:track:3ee8Jmje8o58CHK66QrVC2', 0, 0)
    .then(res => {
          console.log(Spotify.getPlaybackMetadata());
        })
```
results in: 
```
{ nextTrack: null, currentTrack: null, prevTrack: null }
```

Using the async version of getPlaybackMetadata and getPlaybackState results in the same outcome.

Although when printing the getPlaybackState the one field that does update synchronously is the "activeDevice" but the "playing" field doesn't seem to update.

Thank you!

**Comment by lufinkey** [comment]
This is not due to this framework but is actually due to the native Spotify libraries for iOS and Android. This is just how they chose to do that. I completely agree that it makes no sense and is pretty thoughtless, but blame that one on Spotify. Please open an issue on the [iOS SDK](https://github.com/spotify/ios-sdk) or [Android SDK](https://github.com/spotify/android-sdk) repos and let them know that this is a problem.

To circumvent this, you can use the `'play'`, `'trackChange'`, or `'metadataChange'` events to handle when this information is actually received and processed by the library. On those events, you'll receive an event object that contains the playback state and the metadata.

**Comment by Abdul-Miraj** [comment]
Wow, okay yeah that makes no sense. I opened an issue on the Android SDK repo and hopefully it will get resolved :).

Thank you.

**Comment by JakeMotta** [comment]
I'm also having this issue.. Is there an example I can use for using the event emitter for this case? I implemented 'react-native-events' as I see that you're using it for this, but I can't quite manage to receive the events when they occur.

**Comment by lufinkey** [comment]
You can also just use `addListener` and `removeListener`
